# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import battery_service_pb2 as battery__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in battery_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BatteryServiceStub(object):
    """gRPC service: pccs.vehiclestates.services.battery.v1.BatteryService
    Methods: GetBattery (server streaming), GetLatestBattery (unary)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBattery = channel.unary_stream(
                '/pccs.vehiclestates.services.battery.v1.BatteryService/GetBattery',
                request_serializer=battery__service__pb2.GetBatteryRequest.SerializeToString,
                response_deserializer=battery__service__pb2.GetBatteryResponse.FromString,
                _registered_method=True)
        self.GetLatestBattery = channel.unary_unary(
                '/pccs.vehiclestates.services.battery.v1.BatteryService/GetLatestBattery',
                request_serializer=battery__service__pb2.GetBatteryRequest.SerializeToString,
                response_deserializer=battery__service__pb2.GetBatteryResponse.FromString,
                _registered_method=True)


class BatteryServiceServicer(object):
    """gRPC service: pccs.vehiclestates.services.battery.v1.BatteryService
    Methods: GetBattery (server streaming), GetLatestBattery (unary)
    """

    def GetBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BatteryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBattery': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBattery,
                    request_deserializer=battery__service__pb2.GetBatteryRequest.FromString,
                    response_serializer=battery__service__pb2.GetBatteryResponse.SerializeToString,
            ),
            'GetLatestBattery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestBattery,
                    request_deserializer=battery__service__pb2.GetBatteryRequest.FromString,
                    response_serializer=battery__service__pb2.GetBatteryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pccs.vehiclestates.services.battery.v1.BatteryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pccs.vehiclestates.services.battery.v1.BatteryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BatteryService(object):
    """gRPC service: pccs.vehiclestates.services.battery.v1.BatteryService
    Methods: GetBattery (server streaming), GetLatestBattery (unary)
    """

    @staticmethod
    def GetBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pccs.vehiclestates.services.battery.v1.BatteryService/GetBattery',
            battery__service__pb2.GetBatteryRequest.SerializeToString,
            battery__service__pb2.GetBatteryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pccs.vehiclestates.services.battery.v1.BatteryService/GetLatestBattery',
            battery__service__pb2.GetBatteryRequest.SerializeToString,
            battery__service__pb2.GetBatteryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
