# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: battery_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'battery_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import battery_pb2 as battery__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61ttery_service.proto\x12&pccs.vehiclestates.services.battery.v1\x1a\rbattery.proto\",\n\x11GetBatteryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"o\n\x12GetBatteryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12@\n\x07\x62\x61ttery\x18\x03 \x01(\x0b\x32/.pccs.vehiclestates.entities.battery.v1.Battery2\xa4\x02\n\x0e\x42\x61tteryService\x12\x85\x01\n\nGetBattery\x12\x39.pccs.vehiclestates.services.battery.v1.GetBatteryRequest\x1a:.pccs.vehiclestates.services.battery.v1.GetBatteryResponse0\x01\x12\x89\x01\n\x10GetLatestBattery\x12\x39.pccs.vehiclestates.services.battery.v1.GetBatteryRequest\x1a:.pccs.vehiclestates.services.battery.v1.GetBatteryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battery_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBATTERYREQUEST']._serialized_start=80
  _globals['_GETBATTERYREQUEST']._serialized_end=124
  _globals['_GETBATTERYRESPONSE']._serialized_start=126
  _globals['_GETBATTERYRESPONSE']._serialized_end=237
  _globals['_BATTERYSERVICE']._serialized_start=240
  _globals['_BATTERYSERVICE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
