# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_mycars.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_mycars.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15polestar_mycars.proto\x12\x0f\x63\x61r_information\"u\n\nCarDetails\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x06 \x01(\t\x12\x12\n\nmodel_year\x18\x07 \x01(\t\x12\"\n\x1ainstalled_software_version\x18\t \x01(\t\x12\x0e\n\x06market\x18\n \x01(\t\"S\n\nMyCarEntry\x12,\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\x1b.car_information.CarDetails\x12\x17\n\x0fregistration_no\x18\x04 \x01(\t\">\n\x11GetMyCarsResponse\x12)\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\x1b.car_information.MyCarEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_mycars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARDETAILS']._serialized_start=42
  _globals['_CARDETAILS']._serialized_end=159
  _globals['_MYCARENTRY']._serialized_start=161
  _globals['_MYCARENTRY']._serialized_end=244
  _globals['_GETMYCARSRESPONSE']._serialized_start=246
  _globals['_GETMYCARSRESPONSE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
