# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_availability_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_availability_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_availability_pb2 as polestar__availability__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#polestar_availability_service.proto\x12#services.vehiclestates.availability\x1a\x1bpolestar_availability.proto\"1\n\x16GetAvailabilityRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"{\n\x17GetAvailabilityResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12G\n\x0c\x61vailability\x18\x03 \x01(\x0b\x32\x31.services.vehiclestates.availability.Availability2\xbb\x02\n\x13\x41vailabilityService\x12\x8e\x01\n\x0fGetAvailability\x12;.services.vehiclestates.availability.GetAvailabilityRequest\x1a<.services.vehiclestates.availability.GetAvailabilityResponse0\x01\x12\x92\x01\n\x15GetLatestAvailability\x12;.services.vehiclestates.availability.GetAvailabilityRequest\x1a<.services.vehiclestates.availability.GetAvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_availability_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETAVAILABILITYREQUEST']._serialized_start=105
  _globals['_GETAVAILABILITYREQUEST']._serialized_end=154
  _globals['_GETAVAILABILITYRESPONSE']._serialized_start=156
  _globals['_GETAVAILABILITYRESPONSE']._serialized_end=279
  _globals['_AVAILABILITYSERVICE']._serialized_start=282
  _globals['_AVAILABILITYSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
