# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_odometer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_odometer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_odometer_pb2 as polestar__odometer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpolestar_odometer_service.proto\x12\x1fservices.vehiclestates.odometer\x1a\x17polestar_odometer.proto\"-\n\x12GetOdometerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"k\n\x13GetOdometerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12;\n\x08odometer\x18\x03 \x01(\x0b\x32).services.vehiclestates.odometer.Odometer2\x8d\x01\n\x0fOdometerService\x12z\n\x0bGetOdometer\x12\x33.services.vehiclestates.odometer.GetOdometerRequest\x1a\x34.services.vehiclestates.odometer.GetOdometerResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_odometer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETODOMETERREQUEST']._serialized_start=93
  _globals['_GETODOMETERREQUEST']._serialized_end=138
  _globals['_GETODOMETERRESPONSE']._serialized_start=140
  _globals['_GETODOMETERRESPONSE']._serialized_end=247
  _globals['_ODOMETERSERVICE']._serialized_start=250
  _globals['_ODOMETERSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
