# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_mycars_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_mycars_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_mycars_pb2 as polestar__mycars__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpolestar_mycars_service.proto\x12\x0f\x63\x61r_information\x1a\x15polestar_mycars.proto\"+\n\x10GetMyCarsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t2d\n\x0e\x43\x61rInformation\x12R\n\tGetMyCars\x12!.car_information.GetMyCarsRequest\x1a\".car_information.GetMyCarsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_mycars_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMYCARSREQUEST']._serialized_start=73
  _globals['_GETMYCARSREQUEST']._serialized_end=116
  _globals['_CARINFORMATION']._serialized_start=118
  _globals['_CARINFORMATION']._serialized_end=218
# @@protoc_insertion_point(module_scope)
