# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_odometer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_odometer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17polestar_odometer.proto\x12\x1fservices.vehiclestates.odometer\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xc5\x02\n\x08Odometer\x12=\n\ttimestamp\x18\x01 \x01(\x0b\x32*.services.vehiclestates.odometer.Timestamp\x12\x17\n\x0fodometer_meters\x18\x02 \x01(\x05\x12\x1c\n\x14trip_meter_manual_km\x18\x03 \x01(\x02\x12\x1f\n\x17trip_meter_automatic_km\x18\x04 \x01(\x02\x12!\n\x19\x61verage_speed_km_per_hour\x18\x05 \x01(\x05\x12+\n#average_speed_km_per_hour_automatic\x18\x06 \x01(\x05\x12\"\n\x1atrip_meter_since_charge_km\x18\x07 \x01(\x02\x12.\n&average_speed_km_per_hour_since_charge\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_odometer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESTAMP']._serialized_start=60
  _globals['_TIMESTAMP']._serialized_end=103
  _globals['_ODOMETER']._serialized_start=106
  _globals['_ODOMETER']._serialized_end=431
# @@protoc_insertion_point(module_scope)
