# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_precleaning_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_precleaning_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_precleaning_pb2 as polestar__precleaning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"polestar_precleaning_service.proto\x12\"services.vehiclestates.precleaning\x1a\x1apolestar_precleaning.proto\"0\n\x15GetPreCleaningRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"x\n\x16GetPreCleaningResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x45\n\x0cpre_cleaning\x18\x03 \x01(\x0b\x32/.services.vehiclestates.precleaning.PreCleaning2\xa0\x01\n\x12PreCleaningService\x12\x89\x01\n\x0eGetPreCleaning\x12\x39.services.vehiclestates.precleaning.GetPreCleaningRequest\x1a:.services.vehiclestates.precleaning.GetPreCleaningResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_precleaning_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRECLEANINGREQUEST']._serialized_start=102
  _globals['_GETPRECLEANINGREQUEST']._serialized_end=150
  _globals['_GETPRECLEANINGRESPONSE']._serialized_start=152
  _globals['_GETPRECLEANINGRESPONSE']._serialized_end=272
  _globals['_PRECLEANINGSERVICE']._serialized_start=275
  _globals['_PRECLEANINGSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
