# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17polestar_location.proto\x12\x0b\x64tlinternet\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"Z\n\x08Location\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12)\n\ttimestamp\x18\x03 \x01(\x0b\x32\x16.dtlinternet.Timestamp\"Y\n\x12LastParkedLocation\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12\'\n\x08location\x18\x02 \x01(\x0b\x32\x15.dtlinternet.Location\x12\r\n\x05stale\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESTAMP']._serialized_start=40
  _globals['_TIMESTAMP']._serialized_end=83
  _globals['_LOCATION']._serialized_start=85
  _globals['_LOCATION']._serialized_end=175
  _globals['_LASTPARKEDLOCATION']._serialized_start=177
  _globals['_LASTPARKEDLOCATION']._serialized_end=266
# @@protoc_insertion_point(module_scope)
