# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_availability.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpolestar_availability.proto\x12#services.vehiclestates.availability\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xbf\x02\n\x0c\x41vailability\x12\x41\n\ttimestamp\x18\x01 \x01(\x0b\x32..services.vehiclestates.availability.Timestamp\x12T\n\x13\x61vailability_status\x18\x03 \x01(\x0e\x32\x37.services.vehiclestates.availability.AvailabilityStatus\x12R\n\x12unavailable_reason\x18\x04 \x01(\x0e\x32\x36.services.vehiclestates.availability.UnavailableReason\x12\x42\n\nusage_mode\x18\x05 \x01(\x0e\x32..services.vehiclestates.availability.UsageMode*\xda\x01\n\tUsageMode\x12\x1a\n\x16USAGE_MODE_UNSPECIFIED\x10\x00\x12\x18\n\x14USAGE_MODE_ABANDONED\x10\x01\x12\x17\n\x13USAGE_MODE_INACTIVE\x10\x02\x12\x1a\n\x16USAGE_MODE_CONVENIENCE\x10\x03\x12\x15\n\x11USAGE_MODE_ACTIVE\x10\x04\x12\x16\n\x12USAGE_MODE_DRIVING\x10\x05\x12\x18\n\x14USAGE_MODE_ENGINE_ON\x10\x06\x12\x19\n\x15USAGE_MODE_ENGINE_OFF\x10\x07*\xc5\x02\n\x11UnavailableReason\x12\"\n\x1eUNAVAILABLE_REASON_UNSPECIFIED\x10\x00\x12\"\n\x1eUNAVAILABLE_REASON_NO_INTERNET\x10\x01\x12(\n$UNAVAILABLE_REASON_POWER_SAVING_MODE\x10\x02\x12!\n\x1dUNAVAILABLE_REASON_CAR_IN_USE\x10\x03\x12\x33\n/UNAVAILABLE_REASON_OTA_INSTALLATION_IN_PROGRESS\x10\x04\x12:\n6UNAVAILABLE_REASON_STOLEN_VEHICLE_TRACKING_IN_PROGRESS\x10\x05\x12*\n&UNAVAILABLE_REASON_SERVICE_MODE_ACTIVE\x10\x06*\x81\x01\n\x12\x41vailabilityStatus\x12#\n\x1f\x41VAILABILITY_STATUS_UNSPECIFIED\x10\x00\x12!\n\x1d\x41VAILABILITY_STATUS_AVAILABLE\x10\x01\x12#\n\x1f\x41VAILABILITY_STATUS_UNAVAILABLE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USAGEMODE']._serialized_start=436
  _globals['_USAGEMODE']._serialized_end=654
  _globals['_UNAVAILABLEREASON']._serialized_start=657
  _globals['_UNAVAILABLEREASON']._serialized_end=982
  _globals['_AVAILABILITYSTATUS']._serialized_start=985
  _globals['_AVAILABILITYSTATUS']._serialized_end=1114
  _globals['_TIMESTAMP']._serialized_start=68
  _globals['_TIMESTAMP']._serialized_end=111
  _globals['_AVAILABILITY']._serialized_start=114
  _globals['_AVAILABILITY']._serialized_end=433
# @@protoc_insertion_point(module_scope)
