# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_amplimit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_amplimit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_chronos_request_pb2 as polestar__chronos__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17polestar_amplimit.proto\x12!pccs.chronos.messages.amplimit.v1\x1a\x1epolestar_chronos_request.proto\"P\n\x0f\x41mpLimitReading\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x12\n\nupdated_at\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"V\n\x12GetAmpLimitRequest\x12@\n\x07request\x18\x01 \x01(\x0b\x32/.pccs.chronos.messages.common.v1.ChronosRequest\"\xd8\x01\n\x13GetAmpLimitResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x45\n\tamp_limit\x18\x03 \x01(\x0b\x32\x32.pccs.chronos.messages.amplimit.v1.AmpLimitReading\x12M\n\x11pending_amp_limit\x18\x04 \x01(\x0b\x32\x32.pccs.chronos.messages.amplimit.v1.AmpLimitReading\x12\x12\n\nupdated_at\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_amplimit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMPLIMITREADING']._serialized_start=94
  _globals['_AMPLIMITREADING']._serialized_end=174
  _globals['_GETAMPLIMITREQUEST']._serialized_start=176
  _globals['_GETAMPLIMITREQUEST']._serialized_end=262
  _globals['_GETAMPLIMITRESPONSE']._serialized_start=265
  _globals['_GETAMPLIMITRESPONSE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
