# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polestar_location_pb2 as polestar__location__pb2
from . import polestar_location_service_pb2 as polestar__location__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polestar_location_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DtlInternetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastParkedLocation = channel.unary_unary(
                '/dtlinternet.DtlInternetService/GetLastParkedLocation',
                request_serializer=polestar__location__service__pb2.LastParkedLocationRequest.SerializeToString,
                response_deserializer=polestar__location__pb2.LastParkedLocation.FromString,
                _registered_method=True)
        self.StreamLastParkedLocations = channel.unary_stream(
                '/dtlinternet.DtlInternetService/StreamLastParkedLocations',
                request_serializer=polestar__location__service__pb2.LastParkedLocationRequest.SerializeToString,
                response_deserializer=polestar__location__pb2.LastParkedLocation.FromString,
                _registered_method=True)


class DtlInternetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLastParkedLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLastParkedLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DtlInternetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastParkedLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastParkedLocation,
                    request_deserializer=polestar__location__service__pb2.LastParkedLocationRequest.FromString,
                    response_serializer=polestar__location__pb2.LastParkedLocation.SerializeToString,
            ),
            'StreamLastParkedLocations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLastParkedLocations,
                    request_deserializer=polestar__location__service__pb2.LastParkedLocationRequest.FromString,
                    response_serializer=polestar__location__pb2.LastParkedLocation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dtlinternet.DtlInternetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dtlinternet.DtlInternetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DtlInternetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLastParkedLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtlinternet.DtlInternetService/GetLastParkedLocation',
            polestar__location__service__pb2.LastParkedLocationRequest.SerializeToString,
            polestar__location__pb2.LastParkedLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLastParkedLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dtlinternet.DtlInternetService/StreamLastParkedLocations',
            polestar__location__service__pb2.LastParkedLocationRequest.SerializeToString,
            polestar__location__pb2.LastParkedLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
