# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_amplimit_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_amplimit_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_amplimit_pb2 as polestar__amplimit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpolestar_amplimit_service.proto\x12\x18pccs.chronos.services.v1\x1a\x17polestar_amplimit.proto2\x91\x01\n\x0f\x41mpLimitService\x12~\n\x0bGetAmpLimit\x12\x35.pccs.chronos.messages.amplimit.v1.GetAmpLimitRequest\x1a\x36.pccs.chronos.messages.amplimit.v1.GetAmpLimitResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_amplimit_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMPLIMITSERVICE']._serialized_start=87
  _globals['_AMPLIMITSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
