# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_precleaning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_precleaning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apolestar_precleaning.proto\x12\"services.vehiclestates.precleaning\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xbe\x05\n\x0bPreCleaning\x12@\n\ttimestamp\x18\x01 \x01(\x0b\x32-.services.vehiclestates.precleaning.Timestamp\x12K\n\x14last_cycle_completed\x18\x02 \x01(\x0b\x32-.services.vehiclestates.precleaning.Timestamp\x12G\n\x10measurement_date\x18\x03 \x01(\x0b\x32-.services.vehiclestates.precleaning.Timestamp\x12\x41\n\nstarted_at\x18\x04 \x01(\x0b\x32-.services.vehiclestates.precleaning.Timestamp\x12@\n\tending_at\x18\x05 \x01(\x0b\x32-.services.vehiclestates.precleaning.Timestamp\x12I\n\x0erunning_status\x18\x06 \x01(\x0e\x32\x31.services.vehiclestates.precleaning.RunningStatus\x12\x45\n\x0cstart_reason\x18\x07 \x01(\x0e\x32/.services.vehiclestates.precleaning.StartReason\x12\x18\n\x10last_cycle_valid\x18\x08 \x01(\x08\x12\"\n\x1ameasured_air_quality_index\x18\t \x01(\x05\x12&\n\x1emeasured_particulate_matter_25\x18\n \x01(\x05\x12\x1c\n\x14runtime_left_minutes\x18\x0b \x01(\x05\x12<\n\x05\x65rror\x18\r \x01(\x0e\x32-.services.vehiclestates.precleaning.ErrorType*a\n\tErrorType\x12\x1a\n\x16\x45RROR_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x45RROR_TYPE_GENERIC_ERROR\x10\x01\x12\x1a\n\x16\x45RROR_TYPE_INTERRUPTED\x10\x02*h\n\x0bStartReason\x12\x1c\n\x18START_REASON_UNSPECIFIED\x10\x00\x12\x17\n\x13START_REASON_REMOTE\x10\x01\x12\"\n\x1eSTART_REASON_MANUALLY_FROM_CAR\x10\x02*z\n\rRunningStatus\x12\x1e\n\x1aRUNNING_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11RUNNING_STATUS_ON\x10\x01\x12\x16\n\x12RUNNING_STATUS_OFF\x10\x02\x12\x1a\n\x16RUNNING_STATUS_PENDING\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_precleaning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORTYPE']._serialized_start=816
  _globals['_ERRORTYPE']._serialized_end=913
  _globals['_STARTREASON']._serialized_start=915
  _globals['_STARTREASON']._serialized_end=1019
  _globals['_RUNNINGSTATUS']._serialized_start=1021
  _globals['_RUNNINGSTATUS']._serialized_end=1143
  _globals['_TIMESTAMP']._serialized_start=66
  _globals['_TIMESTAMP']._serialized_end=109
  _globals['_PRECLEANING']._serialized_start=112
  _globals['_PRECLEANING']._serialized_end=814
# @@protoc_insertion_point(module_scope)
