# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_chargetimer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_chargetimer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_chargetimer_pb2 as polestar__chargetimer__pb2
from . import polestar_chronos_request_pb2 as polestar__chronos__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"polestar_chargetimer_service.proto\x12\x18pccs.chronos.services.v2\x1a\x1apolestar_chargetimer.proto\x1a\x1epolestar_chronos_request.proto\"e\n!GetGlobalChargeTimerStreamRequest\x12@\n\x07request\x18\x01 \x01(\x0b\x32/.pccs.chronos.messages.common.v1.ChronosRequest2\xc2\x01\n\x18GlobalChargeTimerService\x12\xa5\x01\n\x1aGetGlobalChargeTimerStream\x12;.pccs.chronos.services.v2.GetGlobalChargeTimerStreamRequest\x1aH.pccs.chronos.messages.chargetimer.v2.GetGlobalChargeTimerStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_chargetimer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETGLOBALCHARGETIMERSTREAMREQUEST']._serialized_start=124
  _globals['_GETGLOBALCHARGETIMERSTREAMREQUEST']._serialized_end=225
  _globals['_GLOBALCHARGETIMERSERVICE']._serialized_start=228
  _globals['_GLOBALCHARGETIMERSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
