# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_chargetimer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_chargetimer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apolestar_chargetimer.proto\x12$pccs.chronos.messages.chargetimer.v2\"\x1c\n\x0cScheduleTime\x12\x0c\n\x04hour\x18\x01 \x01(\x05\"\x96\x01\n\x10\x43hargeTimerEntry\x12\x41\n\x05start\x18\x01 \x01(\x0b\x32\x32.pccs.chronos.messages.chargetimer.v2.ScheduleTime\x12?\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x32.pccs.chronos.messages.chargetimer.v2.ScheduleTime\"\x7f\n\"GetGlobalChargeTimerStreamResponse\x12\x45\n\x05timer\x18\x01 \x01(\x0b\x32\x36.pccs.chronos.messages.chargetimer.v2.ChargeTimerEntry\x12\x12\n\nupdated_at\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_chargetimer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULETIME']._serialized_start=68
  _globals['_SCHEDULETIME']._serialized_end=96
  _globals['_CHARGETIMERENTRY']._serialized_start=99
  _globals['_CHARGETIMERENTRY']._serialized_end=249
  _globals['_GETGLOBALCHARGETIMERSTREAMRESPONSE']._serialized_start=251
  _globals['_GETGLOBALCHARGETIMERSTREAMRESPONSE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
