# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polestar_chargetimer_pb2 as polestar__chargetimer__pb2
from . import polestar_chargetimer_service_pb2 as polestar__chargetimer__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polestar_chargetimer_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlobalChargeTimerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalChargeTimerStream = channel.unary_stream(
                '/pccs.chronos.services.v2.GlobalChargeTimerService/GetGlobalChargeTimerStream',
                request_serializer=polestar__chargetimer__service__pb2.GetGlobalChargeTimerStreamRequest.SerializeToString,
                response_deserializer=polestar__chargetimer__pb2.GetGlobalChargeTimerStreamResponse.FromString,
                _registered_method=True)


class GlobalChargeTimerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGlobalChargeTimerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobalChargeTimerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalChargeTimerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetGlobalChargeTimerStream,
                    request_deserializer=polestar__chargetimer__service__pb2.GetGlobalChargeTimerStreamRequest.FromString,
                    response_serializer=polestar__chargetimer__pb2.GetGlobalChargeTimerStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pccs.chronos.services.v2.GlobalChargeTimerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pccs.chronos.services.v2.GlobalChargeTimerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlobalChargeTimerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGlobalChargeTimerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pccs.chronos.services.v2.GlobalChargeTimerService/GetGlobalChargeTimerStream',
            polestar__chargetimer__service__pb2.GetGlobalChargeTimerStreamRequest.SerializeToString,
            polestar__chargetimer__pb2.GetGlobalChargeTimerStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
