# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polestar_parkingclimatization_service_pb2 as polestar__parkingclimatization__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polestar_parkingclimatization_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParkingClimatizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParkingClimatization = channel.unary_stream(
                '/services.vehiclestates.parkingclimatization.ParkingClimatizationService/GetParkingClimatization',
                request_serializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.SerializeToString,
                response_deserializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.FromString,
                _registered_method=True)
        self.GetLatestParkingClimatization = channel.unary_unary(
                '/services.vehiclestates.parkingclimatization.ParkingClimatizationService/GetLatestParkingClimatization',
                request_serializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.SerializeToString,
                response_deserializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.FromString,
                _registered_method=True)


class ParkingClimatizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetParkingClimatization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestParkingClimatization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParkingClimatizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParkingClimatization': grpc.unary_stream_rpc_method_handler(
                    servicer.GetParkingClimatization,
                    request_deserializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.FromString,
                    response_serializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.SerializeToString,
            ),
            'GetLatestParkingClimatization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestParkingClimatization,
                    request_deserializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.FromString,
                    response_serializer=polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.vehiclestates.parkingclimatization.ParkingClimatizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.vehiclestates.parkingclimatization.ParkingClimatizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParkingClimatizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetParkingClimatization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.vehiclestates.parkingclimatization.ParkingClimatizationService/GetParkingClimatization',
            polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.SerializeToString,
            polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestParkingClimatization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.vehiclestates.parkingclimatization.ParkingClimatizationService/GetLatestParkingClimatization',
            polestar__parkingclimatization__service__pb2.GetParkingClimatizationRequest.SerializeToString,
            polestar__parkingclimatization__service__pb2.GetParkingClimatizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
