# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_location_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_location_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_location_pb2 as polestar__location__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpolestar_location_service.proto\x12\x0b\x64tlinternet\x1a\x17polestar_location.proto\"(\n\x19LastParkedLocationRequest\x12\x0b\n\x03vin\x18\x01 \x01(\t2\xde\x01\n\x12\x44tlInternetService\x12`\n\x15GetLastParkedLocation\x12&.dtlinternet.LastParkedLocationRequest\x1a\x1f.dtlinternet.LastParkedLocation\x12\x66\n\x19StreamLastParkedLocations\x12&.dtlinternet.LastParkedLocationRequest\x1a\x1f.dtlinternet.LastParkedLocation0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_location_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LASTPARKEDLOCATIONREQUEST']._serialized_start=73
  _globals['_LASTPARKEDLOCATIONREQUEST']._serialized_end=113
  _globals['_DTLINTERNETSERVICE']._serialized_start=116
  _globals['_DTLINTERNETSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
