# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polestar_exterior_service_pb2 as polestar__exterior__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polestar_exterior_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExteriorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExterior = channel.unary_stream(
                '/services.vehiclestates.exterior.ExteriorService/GetExterior',
                request_serializer=polestar__exterior__service__pb2.GetExteriorRequest.SerializeToString,
                response_deserializer=polestar__exterior__service__pb2.GetExteriorResponse.FromString,
                _registered_method=True)
        self.GetLatestExterior = channel.unary_unary(
                '/services.vehiclestates.exterior.ExteriorService/GetLatestExterior',
                request_serializer=polestar__exterior__service__pb2.GetExteriorRequest.SerializeToString,
                response_deserializer=polestar__exterior__service__pb2.GetExteriorResponse.FromString,
                _registered_method=True)


class ExteriorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExterior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestExterior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExteriorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExterior': grpc.unary_stream_rpc_method_handler(
                    servicer.GetExterior,
                    request_deserializer=polestar__exterior__service__pb2.GetExteriorRequest.FromString,
                    response_serializer=polestar__exterior__service__pb2.GetExteriorResponse.SerializeToString,
            ),
            'GetLatestExterior': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestExterior,
                    request_deserializer=polestar__exterior__service__pb2.GetExteriorRequest.FromString,
                    response_serializer=polestar__exterior__service__pb2.GetExteriorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.vehiclestates.exterior.ExteriorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.vehiclestates.exterior.ExteriorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExteriorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExterior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.vehiclestates.exterior.ExteriorService/GetExterior',
            polestar__exterior__service__pb2.GetExteriorRequest.SerializeToString,
            polestar__exterior__service__pb2.GetExteriorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestExterior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.vehiclestates.exterior.ExteriorService/GetLatestExterior',
            polestar__exterior__service__pb2.GetExteriorRequest.SerializeToString,
            polestar__exterior__service__pb2.GetExteriorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
