# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_health_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_health_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_health_pb2 as polestar__health__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpolestar_health_service.proto\x12\x1dservices.vehiclestates.health\x1a\x15polestar_health.proto\"+\n\x10GetHealthRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"c\n\x11GetHealthResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x35\n\x06health\x18\x03 \x01(\x0b\x32%.services.vehiclestates.health.Health2\x81\x01\n\rHealthService\x12p\n\tGetHealth\x12/.services.vehiclestates.health.GetHealthRequest\x1a\x30.services.vehiclestates.health.GetHealthResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_health_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHEALTHREQUEST']._serialized_start=87
  _globals['_GETHEALTHREQUEST']._serialized_end=130
  _globals['_GETHEALTHRESPONSE']._serialized_start=132
  _globals['_GETHEALTHRESPONSE']._serialized_end=231
  _globals['_HEALTHSERVICE']._serialized_start=234
  _globals['_HEALTHSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
