# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polestar_amplimit_pb2 as polestar__amplimit__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polestar_amplimit_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AmpLimitServiceStub(object):
    """gRPC service: pccs.chronos.services.v1.AmpLimitService (PCCS host).
    Confirmed server-streaming and long-lived (a real call received one valid
    message immediately, then held the connection open past a 15s deadline
    rather than closing) -- read the same way as get_target_soc: first
    message only, not "wait for the stream to end".

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAmpLimit = channel.unary_stream(
                '/pccs.chronos.services.v1.AmpLimitService/GetAmpLimit',
                request_serializer=polestar__amplimit__pb2.GetAmpLimitRequest.SerializeToString,
                response_deserializer=polestar__amplimit__pb2.GetAmpLimitResponse.FromString,
                _registered_method=True)


class AmpLimitServiceServicer(object):
    """gRPC service: pccs.chronos.services.v1.AmpLimitService (PCCS host).
    Confirmed server-streaming and long-lived (a real call received one valid
    message immediately, then held the connection open past a 15s deadline
    rather than closing) -- read the same way as get_target_soc: first
    message only, not "wait for the stream to end".

    """

    def GetAmpLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AmpLimitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAmpLimit': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAmpLimit,
                    request_deserializer=polestar__amplimit__pb2.GetAmpLimitRequest.FromString,
                    response_serializer=polestar__amplimit__pb2.GetAmpLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pccs.chronos.services.v1.AmpLimitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pccs.chronos.services.v1.AmpLimitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AmpLimitService(object):
    """gRPC service: pccs.chronos.services.v1.AmpLimitService (PCCS host).
    Confirmed server-streaming and long-lived (a real call received one valid
    message immediately, then held the connection open past a 15s deadline
    rather than closing) -- read the same way as get_target_soc: first
    message only, not "wait for the stream to end".

    """

    @staticmethod
    def GetAmpLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pccs.chronos.services.v1.AmpLimitService/GetAmpLimit',
            polestar__amplimit__pb2.GetAmpLimitRequest.SerializeToString,
            polestar__amplimit__pb2.GetAmpLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
