# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polestar_parkingclimatization_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polestar_parkingclimatization_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import polestar_parkingclimatization_pb2 as polestar__parkingclimatization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+polestar_parkingclimatization_service.proto\x12+services.vehiclestates.parkingclimatization\x1a#polestar_parkingclimatization.proto\"9\n\x1eGetParkingClimatizationRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"\x9c\x01\n\x1fGetParkingClimatizationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12`\n\x15parking_climatization\x18\x03 \x01(\x0b\x32\x41.services.vehiclestates.parkingclimatization.ParkingClimatization2\x93\x03\n\x1bParkingClimatizationService\x12\xb6\x01\n\x17GetParkingClimatization\x12K.services.vehiclestates.parkingclimatization.GetParkingClimatizationRequest\x1aL.services.vehiclestates.parkingclimatization.GetParkingClimatizationResponse0\x01\x12\xba\x01\n\x1dGetLatestParkingClimatization\x12K.services.vehiclestates.parkingclimatization.GetParkingClimatizationRequest\x1aL.services.vehiclestates.parkingclimatization.GetParkingClimatizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polestar_parkingclimatization_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPARKINGCLIMATIZATIONREQUEST']._serialized_start=129
  _globals['_GETPARKINGCLIMATIZATIONREQUEST']._serialized_end=186
  _globals['_GETPARKINGCLIMATIZATIONRESPONSE']._serialized_start=189
  _globals['_GETPARKINGCLIMATIZATIONRESPONSE']._serialized_end=345
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_start=348
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
