# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: target_soc_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'target_soc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import target_soc_pb2 as target__soc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18target_soc_service.proto\x12\x18pccs.chronos.services.v1\x1a\x10target_soc.proto2\x9e\x02\n\x10TargetSocService\x12\x83\x01\n\x0cGetTargetSoc\x12\x37.pccs.chronos.messages.targetsoc.v1.GetTargetSocRequest\x1a\x38.pccs.chronos.messages.targetsoc.v1.GetTargetSocResponse0\x01\x12\x83\x01\n\x0cSetTargetSoc\x12\x37.pccs.chronos.messages.targetsoc.v1.SetTargetSocRequest\x1a\x38.pccs.chronos.messages.targetsoc.v1.SetTargetSocResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'target_soc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETSOCSERVICE']._serialized_start=73
  _globals['_TARGETSOCSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
