# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: target_soc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'target_soc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chronos_request_pb2 as chronos__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10target_soc.proto\x12\"pccs.chronos.messages.targetsoc.v1\x1a\x15\x63hronos_request.proto\"\xcc\x01\n\tTargetSoc\x12#\n\x1b\x62\x61ttery_charge_target_level\x18\x01 \x01(\x05\x12j\n charge_target_level_setting_type\x18\x02 \x01(\x0e\x32@.pccs.chronos.messages.targetsoc.v1.ChargeTargetLevelSettingType\x12\x12\n\nupdated_at\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\t\"W\n\x13GetTargetSocRequest\x12@\n\x07request\x18\x01 \x01(\x0b\x32/.pccs.chronos.messages.common.v1.ChronosRequest\"\xe5\x01\n\x14GetTargetSocResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x41\n\ntarget_soc\x18\x03 \x01(\x0b\x32-.pccs.chronos.messages.targetsoc.v1.TargetSoc\x12I\n\x12pending_target_soc\x18\x04 \x01(\x0b\x32-.pccs.chronos.messages.targetsoc.v1.TargetSoc\x12\x17\n\nupdated_at\x18\x05 \x01(\x03H\x00\x88\x01\x01\x42\r\n\x0b_updated_at\"\xe8\x01\n\x13SetTargetSocRequest\x12@\n\x07request\x18\x01 \x01(\x0b\x32/.pccs.chronos.messages.common.v1.ChronosRequest\x12#\n\x1b\x62\x61ttery_charge_target_level\x18\x02 \x01(\x05\x12j\n charge_target_level_setting_type\x18\x03 \x01(\x0e\x32@.pccs.chronos.messages.targetsoc.v1.ChargeTargetLevelSettingType\"\"\n\x14SetTargetSocResponse\x12\n\n\x02id\x18\x01 \x01(\t*v\n\x1c\x43hargeTargetLevelSettingType\x12\x30\n,CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05\x44\x41ILY\x10\x01\x12\r\n\tLONG_TRIP\x10\x02\x12\n\n\x06\x43USTOM\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'target_soc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARGETARGETLEVELSETTINGTYPE']._serialized_start=878
  _globals['_CHARGETARGETLEVELSETTINGTYPE']._serialized_end=996
  _globals['_TARGETSOC']._serialized_start=80
  _globals['_TARGETSOC']._serialized_end=284
  _globals['_GETTARGETSOCREQUEST']._serialized_start=286
  _globals['_GETTARGETSOCREQUEST']._serialized_end=373
  _globals['_GETTARGETSOCRESPONSE']._serialized_start=376
  _globals['_GETTARGETSOCRESPONSE']._serialized_end=605
  _globals['_SETTARGETSOCREQUEST']._serialized_start=608
  _globals['_SETTARGETSOCREQUEST']._serialized_end=840
  _globals['_SETTARGETSOCRESPONSE']._serialized_start=842
  _globals['_SETTARGETSOCRESPONSE']._serialized_end=876
# @@protoc_insertion_point(module_scope)
