# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import target_soc_pb2 as target__soc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in target_soc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TargetSocServiceStub(object):
    """Reconstructed from Polestar Android APK v5.5.0 decompilation
    gRPC service: pccs.chronos.services.v1.TargetSocService

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTargetSoc = channel.unary_stream(
                '/pccs.chronos.services.v1.TargetSocService/GetTargetSoc',
                request_serializer=target__soc__pb2.GetTargetSocRequest.SerializeToString,
                response_deserializer=target__soc__pb2.GetTargetSocResponse.FromString,
                _registered_method=True)
        self.SetTargetSoc = channel.unary_stream(
                '/pccs.chronos.services.v1.TargetSocService/SetTargetSoc',
                request_serializer=target__soc__pb2.SetTargetSocRequest.SerializeToString,
                response_deserializer=target__soc__pb2.SetTargetSocResponse.FromString,
                _registered_method=True)


class TargetSocServiceServicer(object):
    """Reconstructed from Polestar Android APK v5.5.0 decompilation
    gRPC service: pccs.chronos.services.v1.TargetSocService

    """

    def GetTargetSoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTargetSoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetSocServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTargetSoc': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTargetSoc,
                    request_deserializer=target__soc__pb2.GetTargetSocRequest.FromString,
                    response_serializer=target__soc__pb2.GetTargetSocResponse.SerializeToString,
            ),
            'SetTargetSoc': grpc.unary_stream_rpc_method_handler(
                    servicer.SetTargetSoc,
                    request_deserializer=target__soc__pb2.SetTargetSocRequest.FromString,
                    response_serializer=target__soc__pb2.SetTargetSocResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pccs.chronos.services.v1.TargetSocService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pccs.chronos.services.v1.TargetSocService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TargetSocService(object):
    """Reconstructed from Polestar Android APK v5.5.0 decompilation
    gRPC service: pccs.chronos.services.v1.TargetSocService

    """

    @staticmethod
    def GetTargetSoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pccs.chronos.services.v1.TargetSocService/GetTargetSoc',
            target__soc__pb2.GetTargetSocRequest.SerializeToString,
            target__soc__pb2.GetTargetSocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTargetSoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pccs.chronos.services.v1.TargetSocService/SetTargetSoc',
            target__soc__pb2.SetTargetSocRequest.SerializeToString,
            target__soc__pb2.SetTargetSocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
